### ISSUE TITLE
[1.16.3] CookieCore fails to load on servers

### ISSUE THREAD

**Issue by NielsPilgaard** [ephys/CookieCore#10]
CookieCore fails to load on servers. 
Crash-report: https://gist.github.com/NillerMedDild/7db2a2979ad3bca2208f64995f0c8cd1

### Versions
- Forge-1.16.3-34.1.25
- cookiecore-1.16.2-3.0.1-a75ceff.jar

**Comment by lyssieth** [comment]
Same error on 1.16.4

Crashlog: [crash-2020-11-15_02.38.43-fml.txt](https://github.com/Ephys/CookieCore/files/5541643/crash-2020-11-15_02.38.43-fml.txt)

**Comment by kil0byt3** [comment]
@Ephys , any movement here? Preventing this mod being used on servers. I know it was the holidays recently, so no rush, but I'd really like to see Magic Feather in Enigmatica 6 :)

**Comment by ephys** [comment]
I missed this notification, I think I accidentally unwatched this repo. Thank you for the ping

I published a fix: https://www.curseforge.com/minecraft/mc-mods/cookiecore/files/3158118

I'm surprised `@EventBusSubscriber` doesn't take `@OnlyIn` into account

**Comment by kil0byt3** [comment]
Thank you very much!
