### ISSUE TITLE
Fix this

### ISSUE THREAD

**Issue by ephys** [ephys/CookieCore#3]
https://github.com/LoveHoly/Ex-Astris/issues/15

**Comment by jermangarc** [comment]
Have same problem here. But mine didn't show up until I installed the new version of Chisel2 (which fixes a Railcraft 9.5 compat issue) that just came out. I tried the CookieCore dev version 1.3.1-5 from jenkins, and got the error below.

http://pastebin.com/PEDAmzVb

**Comment by ephys** [comment]
Oh yeah, forgot to close this. It isn't a cookiecore issue. When this error happens, it means a mod added an itemstack with a null item to a something that uses HashedItemstacks

Anyway, your problem here is an issue in tsteelworks which can't find RC's coke. It's fixed there http://tehnut.info/jenkins/job/TSteelworks/

**Comment by jermangarc** [comment]
Wow! You are lightning fast! Thanks for the reference and dumbing it down for me. Everytime RC comes out with a new version, everything seems to break, lol!
