### ISSUE TITLE
Not Quite Sure?

### ISSUE THREAD

**Issue by KillerInc** [ephys/CookieCore#8]
Failing to set up fuel recipes?
probably wrong place for this could be TSteel?

I'm required buy PLAYER to inform you fastcraft1.19 is installed.
however this previously worked with fastcraft1.19 installed

http://pastebin.com/20FEukWh

**Comment by ephys** [comment]
Tinkers' steelworks issue, see https://github.com/Ephys/TinkersSteelworks/issues/60
