### ISSUE TITLE
CookieCore crashes my friend's modpack

### ISSUE THREAD

**Issue by Ataeraxia** [ephys/CookieCore#9]
Whenever I include cookiecore in my friend's modpack, it crashes, and obviously certain mods don't work without it (I need them to go on said friend's server). I definitely have Java 7. Here's the code: 

Edit: I posted the wrong log the first time, here's the actual log:

> [17:29:48] [main/DEBUG] [FML/]: Injecting tracing printstreams for STDOUT/STDERR.
> [17:29:48] [main/INFO] [FML/]: Forge Mod Loader version 7.10.85.1236 for Minecraft 1.7.10 loading
> [17:29:48] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.9.5, installed at /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
> [17:29:48] [main/DEBUG] [FML/]: Java classpath at launch is /Users/rick/Library/Application Support/technic/modpacks/blocklands-official-classic/bin/modpack.jar:/Users/rick/Library/Application Support/technic/cache/net/minecraft/launchwrapper/1.11/launchwrapper-1.11.jar:/Users/rick/Library/Application Support/technic/cache/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar:/Users/rick/Library/Application Support/technic/cache/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar:/Users/rick/Library/Application Support/technic/cache/com/typesafe/config/1.2.1/config-1.2.1.jar:/Users/rick/Library/Application Support/technic/cache/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar:/Users/rick/Library/Application Support/technic/cache/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar:/Users/rick/Library/Application Support/technic/cache/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar:/Users/rick/Library/Application Support/technic/cache/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar:/Users/rick/Library/Application Support/technic/cache/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar:/Users/rick/Library/Application Support/technic/cache/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar:/Users/rick/Library/Application Support/technic/cache/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar:/Users/rick/Library/Application Support/technic/cache/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar:/Users/rick/Library/Application Support/technic/cache/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar:/Users/rick/Library/Application Support/technic/cache/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar:/Users/rick/Library/Application Support/technic/cache/lzma/lzma/0.0.1/lzma-0.0.1.jar:/Users/rick/Library/Application Support/technic/cache/com/mojang/realms/1.3.5/realms-1.3.5.jar:/Users/rick/Library/Application Support/technic/cache/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/Users/rick/Library/Application Support/technic/cache/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/Users/rick/Library/Application Support/technic/cache/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/Users/rick/Library/Application Support/technic/cache/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/Users/rick/Library/Application Support/technic/cache/java3d/vecmath/1.3.1/vecmath-1.3.1.jar:/Users/rick/Library/Application Support/technic/cache/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar:/Users/rick/Library/Application Support/technic/cache/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:/Users/rick/Library/Application Support/technic/cache/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/Users/rick/Library/Application Support/technic/cache/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/Users/rick/Library/Application Support/technic/cache/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/Users/rick/Library/Application Support/technic/cache/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:/Users/rick/Library/Application Support/technic/cache/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/Users/rick/Library/Application Support/technic/cache/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar:/Users/rick/Library/Application Support/technic/cache/com/google/guava/guava/16.0/guava-16.0.jar:/Users/rick/Library/Application Support/technic/cache/org/apache/commons/commons-lang3/3.2.1/commons-lang3-3.2.1.jar:/Users/rick/Library/Application Support/technic/cache/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/rick/Library/Application Support/technic/cache/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:/Users/rick/Library/Application Support/technic/cache/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/Users/rick/Library/Application Support/technic/cache/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/Users/rick/Library/Application Support/technic/cache/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar:/Users/rick/Library/Application Support/technic/cache/com/mojang/authlib/1.5.16/authlib-1.5.16.jar:/Users/rick/Library/Application Support/technic/cache/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar:/Users/rick/Library/Application Support/technic/cache/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar:/Users/rick/Library/Application Support/technic/cache/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar:/Users/rick/Library/Application Support/technic/cache/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar:/Users/rick/Library/Application Support/technic/cache/tv/twitch/twitch/5.16/twitch-5.16.jar:/Users/rick/Library/Application Support/technic/modpacks/blocklands-official-classic/bin/minecraft.jar
> [17:29:48] [main/DEBUG] [FML/]: Java library path at launch is /Users/rick/Library/Application Support/technic/modpacks/blocklands-official-classic/bin/natives
> [17:29:48] [main/DEBUG] [FML/]: Enabling runtime deobfuscation
> [17:29:48] [main/DEBUG] [FML/]: Instantiating coremod class FMLCorePlugin
> [17:29:48] [main/DEBUG] [FML/]: Added access transformer class cpw.mods.fml.common.asm.transformers.AccessTransformer to enqueued access transformers
> [17:29:48] [main/DEBUG] [FML/]: Enqueued coremod FMLCorePlugin
> [17:29:48] [main/DEBUG] [FML/]: Instantiating coremod class FMLForgePlugin
> [17:29:48] [main/DEBUG] [FML/]: Added access transformer class net.minecraftforge.transformers.ForgeAccessTransformer to enqueued access transformers
> [17:29:48] [main/DEBUG] [FML/]: Enqueued coremod FMLForgePlugin
> [17:29:48] [main/DEBUG] [FML/]: All fundamental core mods are successfully located
> [17:29:48] [main/DEBUG] [FML/]: Attempting to load commandline specified mods, relative to /Users/rick/Library/Application Support/technic/modpacks/blocklands-official-classic
> [17:29:48] [main/DEBUG] [FML/]: Discovering coremods
> [17:29:48] [main/DEBUG] [FML/]: Examining for coremod candidacy [1.7.10]bspkrsCore-universal-6.15.jar
> [17:29:48] [main/DEBUG] [FML/]: Not found coremod data in [1.7.10]bspkrsCore-universal-6.15.jar
> [17:29:48] [main/DEBUG] [FML/]: Examining for coremod candidacy [1.7.10]Treecapitator-universal-2.0.4.jar
> [17:29:48] [main/DEBUG] [FML/]: Not found coremod data in [1.7.10]Treecapitator-universal-2.0.4.jar
> [17:29:48] [main/DEBUG] [FML/]: Examining for coremod candidacy AOBD-2.4.0.jar
> [17:29:48] [main/DEBUG] [FML/]: Not found coremod data in AOBD-2.4.0.jar
> [17:29:48] [main/DEBUG] [FML/]: Examining for coremod candidacy AppleCore-mc1.7.10-1.1.0.jar
> [17:29:48] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.7.10-1.1.0.jar, it will be examined later for regular @Mod instances
> [17:29:48] [main/DEBUG] [FML/]: Instantiating coremod class AppleCore
> [17:29:48] [main/DEBUG] [FML/]: The coremod squeek.applecore.AppleCore requested minecraft version 1.7.10 and minecraft is 1.7.10. It will be loaded.
> [17:29:48] [main/DEBUG] [FML/]: Enqueued coremod AppleCore
> [17:29:48] [main/DEBUG] [FML/]: Examining for coremod candidacy appliedenergistics2-rv1-stable-1.jar
> [17:29:48] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in appliedenergistics2-rv1-stable-1.jar, it will be examined later for regular @Mod instances
> [17:29:48] [main/DEBUG] [FML/]: Instantiating coremod class AppEngCore
> [17:29:48] [main/WARN] [FML/]: The coremod appeng.transformer.AppEngCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [17:29:48] [main/INFO] [FML/]: [AppEng] Core Init
> [17:29:48] [main/DEBUG] [FML/]: Added access transformer class appeng.transformer.asm.ASMTweaker to enqueued access transformers
> [17:29:48] [main/DEBUG] [FML/]: Enqueued coremod AppEngCore
> [17:29:48] [main/DEBUG] [FML/]: Examining for coremod candidacy Chisel2-2.3.5.31.jar
> [17:29:48] [main/DEBUG] [FML/]: Not found coremod data in Chisel2-2.3.5.31.jar
> [17:29:48] [main/DEBUG] [FML/]: Examining for coremod candidacy CodeChickenCore-1.7.10-1.0.4.29-universal.jar
> [17:29:48] [main/TRACE] [FML/]: Adding CodeChickenCore-1.7.10-1.0.4.29-universal.jar to the list of known coremods, it will not be examined again
> [17:29:48] [main/DEBUG] [FML/]: Instantiating coremod class CodeChickenCorePlugin
> [17:29:48] [main/WARN] [FML/]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [17:29:49] [main/DEBUG] [FML/]: Added access transformer class codechicken.core.asm.CodeChickenAccessTransformer to enqueued access transformers
> [17:29:49] [main/DEBUG] [FML/]: Enqueued coremod CodeChickenCorePlugin
> [17:29:49] [main/DEBUG] [FML/]: Examining for coremod candidacy CodeChickenLib-1.7.10-1.1.1.99-universal.jar
> [17:29:49] [main/DEBUG] [FML/]: Not found coremod data in CodeChickenLib-1.7.10-1.1.1.99-universal.jar
> [17:29:49] [main/DEBUG] [FML/]: Examining for coremod candidacy CookieCore-1.7.10-1.3.1-5.jar
> [17:29:49] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in CookieCore-1.7.10-1.3.1-5.jar, it will be examined later for regular @Mod instances
> [17:29:49] [main/DEBUG] [FML/]: Instantiating coremod class CookieCoreASM
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:461]: java.lang.UnsupportedClassVersionError: nf/fr/ephys/cookiecore/common/CookieCoreASM : Unsupported major.minor version 51.0
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.lang.ClassLoader.defineClass1(Native Method)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.security.AccessController.doPrivileged(Native Method)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.lang.Class.forName0(Native Method)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.lang.Class.forName(Class.java:249)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> [17:29:49] [main/ERROR] [FML/]: An error occurred trying to configure the minecraft home at /Users/rick/Library/Application Support/technic/modpacks/blocklands-official-classic for Forge Mod Loader
> java.lang.UnsupportedClassVersionError: nf/fr/ephys/cookiecore/common/CookieCoreASM : Unsupported major.minor version 51.0
>     at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_65]
>     at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) ~[?:1.6.0_65]
>     at java.lang.ClassLoader.defineClass(ClassLoader.java:621) ~[?:1.6.0_65]
>     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) ~[?:1.6.0_65]
>     at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) ~[?:1.6.0_65]
>     at java.net.URLClassLoader.access$000(URLClassLoader.java:58) ~[?:1.6.0_65]
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:197) ~[?:1.6.0_65]
>     at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_65]
>     at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[?:1.6.0_65]
>     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.11.jar:?]
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
>     at java.lang.Class.forName0(Native Method) ~[?:1.6.0_65]
>     at java.lang.Class.forName(Class.java:249) ~[?:1.6.0_65]
>     at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417) ~[modpack.jar:?]
>     at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346) ~[modpack.jar:?]
>     at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214) ~[modpack.jar:?]
>     at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [modpack.jar:?]
>     at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [modpack.jar:?]
>     at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [modpack.jar:?]
>     at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [modpack.jar:?]
>     at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
>     at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:461]: java.lang.UnsupportedClassVersionError: nf/fr/ephys/cookiecore/common/CookieCoreASM : Unsupported major.minor version 51.0
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.lang.ClassLoader.defineClass1(Native Method)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.security.AccessController.doPrivileged(Native Method)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.lang.Class.forName0(Native Method)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at java.lang.Class.forName(Class.java:249)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
> [17:29:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]:    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by ephys** [comment]
Hello !

You might have java 7 installed but you launched minecraft using java 6 

```
Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, 
```

**Comment by Ataeraxia** [comment]
Omg, no way! What a stupid mistake! So uh, how do I make sure I'm using the right Java? I'm pretty sure I deleted the right files when I installed it...? I'm on a Mac by the way.

Thank you so much for your quick and kind response :)

**Comment by ephys** [comment]
I've never used a mac in my life so I wouldn't know sorry :/
